package models.dao;

import java.awt.RadialGradientPaint;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;

import enums.Role;
import enums.Visibility;
import models.Repository;
import services.DBconnection;

public class RepositoryDAO {

	static RepositoryDAO repositoryDAO = null;

	private RepositoryDAO() {

	}

	public static RepositoryDAO getInstance() {
		if(repositoryDAO == null) {
			repositoryDAO = new RepositoryDAO();
		}
		return repositoryDAO;
	}

	public boolean addRepository(String name, String description, String visibility, int owner_id){
		try {
			Connection connection = DBconnection.getConnection();
			PreparedStatement stmt = connection.prepareStatement("insert into repositories(name,visibility,owner_id,description) values(?,?,?,?)",Statement.RETURN_GENERATED_KEYS);
			stmt.setString(1, name);
			stmt.setString(2, Visibility.valueOf(visibility).toString());
			stmt.setInt(3, owner_id);
			stmt.setString(4, description);
			int affected = stmt.executeUpdate();
			int repo_id = -1;
			
			// getting the repository key which is generated by mysql database.
			ResultSet keys = stmt.getGeneratedKeys();
			if(keys.next()) {
				repo_id = keys.getInt(1);
			}
			
			// Maping the Repository with user in repository_access table if repository added.
			if(affected>0) {
				mapRepository(owner_id, repo_id , Role.OWNER);
				return affected>0;
			}
		
		} catch (Exception e) {
			e.printStackTrace();
		}
		return false;
	}
	
	public ArrayList<Repository> getAllRepositoryExceptCurrentUser(int userId){
		ArrayList<Repository> repositories = new ArrayList<Repository>();
		try {
			Connection connection = DBconnection.getConnection();
			PreparedStatement stmt = connection.prepareStatement("select r.id, r.name, r.description, r.createdAt, r.stars_count ,u1.username from repositories r join users u1 on r.owner_id = u1.id where r.owner_id != ? and r.visibility = ? ");
			stmt.setInt(1, userId);
			stmt.setString(2, Visibility.PUBLIC.toString());
			ResultSet rs = stmt.executeQuery();
			while(rs.next()) {
				Repository repository = new Repository(rs.getInt(1),rs.getString(2),Visibility.PUBLIC,rs.getString(3),rs.getTimestamp(4).toLocalDateTime(),rs.getInt(5));
				repository.setOwnerName(rs.getString(6));
				repositories.add(repository);
			}
			
		} catch (Exception e) {
			System.out.println("Get all repositories except current user : "+e.getMessage());
		}
		return repositories;
	}

	public ArrayList<Repository> repositoriesByOwnerId(int ownerId){
		ArrayList<Repository> repositories = new ArrayList<Repository>();
		try {
			Connection connection = DBconnection.getConnection();
			PreparedStatement stmt = connection.prepareStatement("select * from repositories where owner_id = ?");
			stmt.setInt(1, ownerId);
			ResultSet rs = stmt.executeQuery();
			if(rs.next()) {
				repositories.add(new Repository(rs.getInt(1),rs.getString(2),Visibility.valueOf(rs.getString(3)),rs.getString(7),rs.getTimestamp(4).toLocalDateTime(),rs.getInt(6)));
			}

		} catch (Exception e) {
			System.out.println(e.getMessage());
		}
		return repositories;
	}
	
	// Takes all the repositories in which the user id exists in any roles.
	public ArrayList<Repository> getAllRepositoryOfUser(int id) {
		ArrayList<Repository> repositories = new ArrayList<Repository>();
		try {
			Connection connection = DBconnection.getConnection();
			PreparedStatement stmt = connection.prepareStatement("select r.id,r.name,r.description,r.visibility,r.createdAt,r.stars_count from repositories r join repository_access ra on r.id=ra.repo_id join users u on u.id = ra.user_id where ra.user_id=?");
			stmt.setInt(1, id);
			ResultSet rs = stmt.executeQuery();
			while(rs.next()) {
		
				repositories.add(new Repository(rs.getInt(1), rs.getString(2), Visibility.valueOf(rs.getString(4)), rs.getString(3), rs.getTimestamp(5).toLocalDateTime(), rs.getInt(6)));
			}
		} catch (Exception e) {
			System.out.println("Getting all repositories : "+e.getMessage());
		}
		return repositories;
	}
	
	// Getting repository details using repository Id.
	public Repository getRepository(int id) {
		Repository repository = null;
		try {
			Connection connection = DBconnection.getConnection();
			PreparedStatement stmt = connection.prepareStatement("select * from repositories where id = ?");
			stmt.setInt(1, id);
			ResultSet rs = stmt.executeQuery();
			if(rs.next()) {
				repository = new Repository(rs.getInt(1),rs.getString(2),Visibility.valueOf(rs.getString(3)),rs.getString(7),rs.getTimestamp(4).toLocalDateTime(),rs.getInt(6));
			}
		} catch (Exception e) {
			System.out.println(e.getMessage());
		}
		return repository;
	}
	
	public int getRepositoryId(String repoName) {
		int id = -1;
		try {
			Connection connection = DBconnection.getConnection();
			PreparedStatement stmt = connection.prepareStatement("select id from repositories where name = ?");
			stmt.setString(1, repoName);
			ResultSet rs = stmt.executeQuery();
			if(rs.next()) {
				id = rs.getInt(1);
			}
		} catch (Exception e) {
			System.out.println("Get Repository Id : "+e.getMessage());
		}
		
		return id;
	}
	
	
	// To Map repositories with the users using repositoy_access database.
	public void mapRepository (int user_id,int repo_id,Role role) {
		try {
			Connection connection = DBconnection.getConnection();
			PreparedStatement stmt = connection.prepareStatement("insert into repository_access(user_id,repo_id,role) values(?,?,?)");
			stmt.setInt(1, user_id);
			stmt.setInt(2, repo_id);
			stmt.setString(3, role.toString());
			stmt.executeUpdate();
			
		} catch (Exception e) {
			e.printStackTrace();
		}
	}
	
	public void addStar(int userId, int repoId) {
		try {
			Connection connection = DBconnection.getConnection();
			PreparedStatement stmt = null;
			
			if(needToMap(userId,repoId)) {
				stmt = connection.prepareStatement("update repositories set stars_count = stars_count+1 where id = ?");
				stmt.setInt(1, repoId);
			}
			else {
				stmt = connection.prepareStatement("update repositories set stars_count = stars_count-1 where id = ?");
				stmt.setInt(1, repoId);
			}
			
			stmt.executeUpdate();
			
		} catch (Exception e) {
			System.out.println("Add star : "+e.getMessage());
		}
	}
	
	public boolean needToMap(int userId, int repoId) {
		
		boolean needToMap = false;
		
		try {
			Connection connection = DBconnection.getConnection();
			PreparedStatement stmt = null;
			if(isStarred(userId,repoId)) {
				stmt = connection.prepareStatement("delete from repo_stared_details where userid = ? and repoid = ?");
				stmt.setInt(1, userId);
				stmt.setInt(2, repoId);
			}
			else {
				stmt = connection.prepareStatement("insert into repo_stared_details values(?,?)");
				stmt.setInt(1, userId);
				stmt.setInt(2, repoId);
				needToMap = true;
			}
			
			stmt.executeUpdate();
			
		} catch (Exception e) {
			System.out.println("Map star : "+e.getMessage());
		}
		
		return needToMap;
	}
	
	public boolean isStarred(int userId, int repoId) {
		try {
			Connection connection = DBconnection.getConnection();
			PreparedStatement stmt = connection.prepareStatement("select * from repo_stared_details where userid = ? and repoid =?");
			stmt.setInt(1, userId);
			stmt.setInt(2, repoId);
			ResultSet rs = stmt.executeQuery();
			if(rs.next()) {
				return true;
			}
		} catch (Exception e) {
			System.out.println("Is starred : "+e.getMessage());
		}
		
		return false;
	}
	
	public ArrayList<Repository> getStarredRepositoriesByUser(int userid){
		ArrayList<Repository> repositoryList = new ArrayList<Repository>();
		try {
			Connection connection = DBconnection.getConnection();
			PreparedStatement stmt = connection.prepareStatement("select r.id,r.name,r.description,r.visibility,r.createdAt,r.stars_count from repositories r join repo_stared_details rs on r.id=rs.repoid join users u on u.id = rs.userid where rs.userid=?");
			stmt.setInt(1, userid);
			ResultSet rs = stmt.executeQuery();
			while(rs.next()) {
				repositoryList.add(new Repository(rs.getInt(1), rs.getString(2), Visibility.valueOf(rs.getString(4)), rs.getString(3), rs.getTimestamp(5).toLocalDateTime(), rs.getInt(6)));
			}
		} catch (Exception e) {
			System.out.println("Get starred repositories : "+e.getMessage());
		}
		
		return repositoryList;
	}
	
	public String getOwnerName(int repoId) {
		String ownerName = null;
		try {
			Connection connection = DBconnection.getConnection();
			PreparedStatement stmt = connection.prepareStatement("select username from users u join repositories r on u.id = r.owner_id where r.id = ?");
			stmt.setInt(1, repoId);
			ResultSet rs = stmt.executeQuery();
			if(rs.next()) {
				ownerName = rs.getString(1);
			}
		} catch (Exception e) {	
			System.out.println("Get owner name : "+e.getMessage());
		}
		
		return ownerName;
	}
	
	public boolean isRepositoryLikedByUser(int repoId, int userId) {
		boolean isLiked = false;
		try {
			Connection connection = DBconnection.getConnection();
			PreparedStatement stmt = connection.prepareStatement("select * from repo_stared_details where repoid = ? and userid = ?");
			stmt.setInt(1, repoId);
			stmt.setInt(2, userId);
			ResultSet rs = stmt.executeQuery();
			isLiked = rs.next();
		} catch (Exception e) {
			System.out.println("Is repository like by user : "+e.getMessage());
		}
		
		return isLiked;
	}

}
